import Link from 'next/link';
import { ArrowLeft, BusFront, CheckCircle2, Clock3, MapPin, ShieldCheck } from 'lucide-react';
import { destinations } from '@/lib/data';

export function generateStaticParams(){ return destinations.map(d=>({slug:d.slug})); }

export default async function RouteDetails({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params; const d=destinations.find(x=>x.slug===slug);
  if(!d) return <main className="container" style={{padding:'100px 0'}}><h1>الوجهة غير موجودة</h1><Link href="/routes">العودة للوجهات</Link></main>;
  return <main style={{paddingBottom:90}}><section style={{minHeight:520,color:'#fff',display:'flex',alignItems:'end',background:`linear-gradient(180deg,rgba(4,16,25,.2),rgba(4,16,25,.9)),url(${d.image}) center/cover`}}><div className="container" style={{padding:'60px 0'}}><Link href="/routes" style={{display:'inline-flex',gap:8,alignItems:'center',opacity:.8}}>كل الوجهات <ArrowLeft size={16}/></Link><span className="english" style={{display:'block',marginTop:35,fontSize:12,letterSpacing:2,color:'var(--sand)'}}>{d.en}</span><h1 style={{fontSize:'clamp(52px,8vw,92px)',margin:'6px 0'}}>{d.name}</h1><p style={{fontSize:18,opacity:.8,maxWidth:600}}>{d.description}</p></div></section>
  <div className="container" style={{paddingTop:55,display:'grid',gridTemplateColumns:'1.25fr .75fr',gap:40}}><section><span style={{color:'var(--sea)',fontWeight:700,fontSize:13}}>CAIRO → {d.en}</span><h2 style={{fontSize:38,margin:'10px 0 15px'}}>رحلة واضحة من البداية.</h2><p style={{color:'var(--muted)',lineHeight:2}}>صفحة المسار مصممة لتعرض للعميل كل ما يحتاجه قبل الحجز: نقطة الانطلاق، الوصول، مدة الرحلة، المواعيد، السعر، نوع السيارة وسياسة الحجز.</p><div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:12,marginTop:30}}>{[['نقطة الانطلاق','القاهرة'],['الوصول',d.name],['المدة','ستحدد من التشغيل'],['المركبة','حسب جدول الأسطول']].map(x=><div key={x[0]} style={{padding:20,background:'#fff',border:'1px solid var(--line)',borderRadius:18}}><span style={{fontSize:12,color:'var(--muted)'}}>{x[0]}</span><strong style={{display:'block',marginTop:7}}>{x[1]}</strong></div>)}</div><h3 style={{fontSize:25,marginTop:45}}>ما ستحصل عليه</h3>{['رحلة منظمة','حجز إلكتروني','دفع آمن عند تفعيل البوابة','تذكرة رقمية بعد تأكيد الحجز'].map(x=><div key={x} style={{padding:'14px 0',borderBottom:'1px solid var(--line)'}}><CheckCircle2 size={17} color="var(--sea" ) style={{verticalAlign:'middle',marginLeft:8}}/>{x}</div>)}</section><aside style={{background:'var(--navy)',color:'#fff',borderRadius:28,padding:30,height:'fit-content',position:'sticky',top:20}}><BusFront size={25}/><h3 style={{fontSize:25,margin:'16px 0 7px'}}>ابحث عن رحلة</h3><p style={{color:'rgba(255,255,255,.6)',lineHeight:1.8,fontSize:14}}>المواعيد والأسعار ستظهر بمجرد إدخال بيانات التشغيل.</p><Link href="/?booking=1" style={{display:'block',textAlign:'center',background:'var(--sand)',color:'var(--ink)',padding:15,borderRadius:15,fontWeight:700,marginTop:25}}>ابدأ البحث <ArrowLeft size={16} style={{verticalAlign:'middle',marginRight:5}}/></Link><div style={{marginTop:25,fontSize:12,color:'rgba(255,255,255,.5)',display:'grid',gap:12}}><span><ShieldCheck size={15} style={{verticalAlign:'middle',marginLeft:7}}/>دفع آمن عند التفعيل</span><span><MapPin size={15} style={{verticalAlign:'middle',marginLeft:7}}/>من القاهرة إلى {d.name}</span><span><Clock3 size={15} style={{verticalAlign:'middle',marginLeft:7}}/>مواعيد قابلة للإدارة</span></div></aside></div></main>
}
